<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<IsAotCompatible>true</IsAotCompatible>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<NoWarn>$(NoWarn);CS1591</NoWarn>
	<AssemblyName>Chhaugen.$(MSBuildProjectName)</AssemblyName>
	<RootNamespace>Chhaugen.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Refit" Version="15.2.0" />
  </ItemGroup>

</Project>
